name: mmoAuction
main: mmo.Auction.MMOAuction
version: 0.1
website: http://forums.bukkit.org/threads/
author: Rycochet <rycochet@rycochet.com>
depend: [mmoCore]

description: Standard mmo auction house.
