name: mmoAuction
version: ${releaseVersion} b${buildNumber}
description: Standard mmo auction house.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Auction.MMOAuction
depend: [Spout, mmoCore]
